# Generated by Django 3.2.8 on 2021-11-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wameedh', '0004_auto_20211101_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bootcamp',
            old_name='Title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='edition',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubevents',
            name='edition',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
