# Generated by Django 3.2.8 on 2021-11-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wameedh', '0006_gallery_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=1, upload_to='projects'),
            preserve_default=False,
        ),
    ]
