# Generated by Django 3.2.8 on 2021-11-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wameedh', '0007_project_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.RemoveField(
            model_name='members',
            name='photo',
        ),
        migrations.AddField(
            model_name='members',
            name='image1',
            field=models.ImageField(default=1, upload_to='memebers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='image2',
            field=models.ImageField(default=1, upload_to='memebers'),
            preserve_default=False,
        ),
    ]
