# Generated by Django 3.2.8 on 2021-11-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wameedh', '0008_auto_20211101_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='order',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], max_length=2, null=True),
        ),
    ]
